# Site Settings
lang: en
title: 
tagline: Bulma Clean Theme
description: > # you can add a website description 
  Next Expense Website
baseurl:
url:
permalink: pretty

logo: Icon-512.png # The image file can be set by placing the image in the main repository


background-color: 31668F

paginate: 5
paginate_path: "/blog/page:num"

# place image in the "img" folder of the repository
hero-img: Updated_test_gif.gif
#change email from here
email: contact@nextexpense.ca
#change phone number from here
phone-number: +1 1111111

#change address from here
address-1: 33 City Centre Dr.
address-2: Mississauga ON, Canada
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "C.S. Rhymes"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
